### ISSUE TITLE
DreamPie seems to have moved

### ISSUE THREAD

**Issue by larkost** [bpython/bsite#18]
On the [Alternatives page](https://bpython-interpreter.org/alternatives.html) on the website the link to DreamPie seem to have gone stale (goes to a more generic source forge page). A google search turns up this as the new page: https://github.com/noamraph/dreampie (http://www.dreampie.org/ gives an error for me).

**Comment by sebastinas** [comment]
Fixed in 905ca02cd0f72a2c79c8bcf0507ef47db0da1221
