### ISSUE TITLE
site still has old name for Recurse Center

### ISSUE THREAD

**Issue by zachvalenta** [bpython/bsite#9]
[this commit](https://github.com/bpython/bsite/commit/263a02f6a6e7a77b7d390c6c0b96655cb2503bcc) changed 'Hacker School' to 'Recurse Center'

but site still seems behind ⬇️

![screen shot 2019-01-24 at 1 33 53 pm](https://user-images.githubusercontent.com/11388735/51700306-c92dd100-1fdc-11e9-9ba5-3bc82efc19a1.png)

**Comment by ikanobori** [comment]
Done and deployed.

**Comment by thomasballinger** [comment]
Thanks @zachvalenta! It has been 4 years, seems about time :)

**Comment by zachvalenta** [comment]
np!
